### ISSUE TITLE
toggleUnread change

### ISSUE THREAD

**Issue by lawiedc** [Elv1zz/ttrss_plugin-markasread#5]
I've been using this plugin happily ever since it was created - and it looks like recent changes in the base code require a change here.

The "bare code" for toggleUnread in markasread.js now needs to explicitly show that is a method from Headlines.

                // toggle the articles unread state
                //  Unread will become Read
                //  Read will become Unread
                Headlines.toggleUnread(articleId);

It looks like another change is also needed to uncheck the tick box - but I can't quite see what that is.

**Comment by TheMagican** [comment]
I am also affected by this. I have forked the repo and implemented the fix you suggested.

Could you explain what you mean by "another change is also needed to uncheck the tick box"? Which tick box do you mean? The one on the right hand side to toggle the read-state ("Mark as read")? If yes: For me both the read-state and the tick box toggles. Works as desired...

**Comment by Elv1zz** [comment]
Hi and thanks to both of you!
Changes seem straight forward to me. There should be no additional changes required for the check box to change its state, as this is implemented purely using CSS styles, no additional JavaScript required.

@TheMagican as you already did the changes required, please just go ahead and create a pull request for that so I can integrate your commit.

**Comment by Elv1zz** [comment]
@TheMagican Thanks for the quick PR! 
@lawiedc Just ho ahead and fork stuff. It's your repository then and you cannot break stuff. 😉 

Let's see if things keep working for another 6 years before the next breaking change appears 😄
